[package]
name = "nasdaq_centrality"
version = "0.1.0"
edition = "2021"

[lib]
name = "nasdaq_centrality"
path = "src/lib.rs"

[dependencies]
petgraph = "0.8"    #
csv      = "1.1"

[dev-dependencies]
tempfile = "3"